# MAINTAINER        qingbo.liu<260831882@qq.com>
# DOCKER-VERSION    17.06.2-ce

FROM          jdk:1.7
MAINTAINER   qingbo.liu<260831882@qq.com>

ADD jdk-8u151-linux-x64.tar.gz /home/jdk/

ENV JAVA_VERSION 1.8.0_151
ENV JAVA_HOME /home/jdk/jdk1.8.0_151

ENV PATH $PATH:$JAVA_HOME/bin